INSERT INTO socks (product_name, price, sex, description, available_amount, size)
VALUES ('Sock1', 1.50, 'MALE', 'Men\'s socks', 97, 'XS'),
       ('Sock2', 2.00, 'MALE', 'Men\'s socks', 15, 'S'),
       ('Sock3', 4.99, 'MALE', 'Men\'s socks', 200, 'M'),
       ('Sock4', 6.99, 'MALE', 'Men\'s socks', 250, 'L'),
       ('Sock5', 9.00, 'MALE', 'Men\'s socks', 54, 'XL'),
       ('Sock6', 2.45, 'MALE', 'Men\'s socks', 30, 'XXL'),
       ('Sock7', 4.12, 'MALE', 'Men\'s socks', 400, 'ONE_SIZE'),
       ('Sock8', 1.56, 'FEMALE', 'Women\'s socks', 3, 'XS'),
       ('Sock9', 2.89, 'FEMALE', 'Women\'s socks', 56, 'S'),
       ('Sock10', 4.05, 'FEMALE', 'Women\'s socks', 200, 'M'),
       ('Sock11', 6.00, 'FEMALE', 'Women\'s socks', 20, 'L'),
       ('Sock12', 8.23, 'FEMALE', 'Women\'s socks', 300, 'XL'),
       ('Sock13', 2.66, 'FEMALE', 'Women\'s socks', 98, 'XXL'),
       ('Sock14', 9.78, 'FEMALE', 'Women\'s socks', 40, 'ONE_SIZE'),
       ('Sock15', 1.99, 'UNISEX', 'Unisex socks', 3, 'XS'),
       ('Sock16', 2.99, 'UNISEX', 'Unisex socks', 150, 'S'),
       ('Sock17', 4.99, 'UNISEX', 'Unisex socks', 20, 'M'),
       ('Sock18', 0.99, 'UNISEX', 'Unisex socks', 22, 'L'),
       ('Sock19', 1.99, 'UNISEX', 'Unisex socks', 30, 'XL'),
       ('Sock20', 22.99, 'UNISEX', 'Unisex socks', 37, 'XXL'),
       ('Sock21', 2.34, 'UNISEX', 'Unisex socks', 40, 'ONE_SIZE');

INSERT INTO outerwear (product_name, price, sex, description, available_amount, type)
VALUES
    ('Male T-Shirt', 24.99, 'MALE', 'Men\'s T-shirt', 100, 'T_SHIRT'),
    ('Male Pants', 34.23, 'MALE', 'Men\'s Pants', 12, 'PANTS'),
    ('Male Jacket', 21.24, 'MALE', 'Men\'s Jacket', 87, 'JACKET'),
    ('Male T-Shirt With Smile', 21.34, 'MALE', 'Men\'s Smile T-shirt', 32, 'T_SHIRT'),
    ('Male Pants Fit', 16.67, 'MALE', 'Men\'s Fit Pants', 69, 'PANTS'),
    ('Male Jacket Heated', 75.89, 'MALE', 'Men\'s Heated Jacket', 35, 'JACKET'),
    ('Female T-Shirt', 24.99, 'FEMALE', 'Women\'s T-shirt', 100, 'T_SHIRT'),
    ('Female Pants', 39.99, 'FEMALE', 'Women\'s Pants', 55, 'PANTS'),
    ('Female Jacket', 5.59, 'FEMALE', 'Women\'s Jacket', 2, 'JACKET'),
    ('Female T-Shirt Slim', 2.78, 'FEMALE', 'Women\'s Slim T-shirt', 78, 'T_SHIRT'),
    ('Female Pants Long', 23.45, 'FEMALE', 'Women\'s Long Pants', 23, 'PANTS'),
    ('Female Jacket Heated', 9.66, 'FEMALE', 'Women\'s Heated Jacket', 90, 'JACKET'),
    ('Unisex T-Shirt', 24.99, 'UNISEX', 'Unisex T-shirt', 4546, 'T_SHIRT'),
    ('Unisex Pants', 7.99, 'UNISEX', 'Unisex Pants', 65, 'PANTS'),
    ('Unisex Jacket', 21.99, 'UNISEX', 'Unisex Jacket', 2, 'JACKET'),
    ('Unisex T-Shirt Shorten', 9.9, 'UNISEX', 'Unisex shorten T-shirt', 23, 'T_SHIRT'),
    ('Unisex Pants Drawing', 34.2, 'UNISEX', 'Unisex drawing Pants', 96, 'PANTS'),
    ('Unisex Jacket Solid', 7.83, 'UNISEX', 'Unisex solid Jacket', 37, 'JACKET');