server:
  port: 8888

spring:
  application:
    name: ox-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MasakDirt/order-xpress-config
          search-paths: '{application}'