server:
  port: 8888

spring:
  application:
    name: ox-config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///C:/Maks/ForWork/Project/order-xpress/ox-config-service/src/main/resources/config