services:
  postgres:
    container_name: postgres-ox
    image: postgres
    environment:
      POSTGRES_USER: ox_user
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-ox
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: ox-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  schema-creator:
    image: mysql
    container_name: ox-schema-creator-mysql
    volumes:
      - ./init_mysql.sh:/init_mysql.sh
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - "chmod +x /init_mysql.sh && /init_mysql.sh && mysql -f"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
    depends_on:
      - mysql

  cassandra:
    image: cassandra
    container_name: ox-cassandra
    environment:
      - CASSANDRA_USER=user
      - CASSANDRA_PASSWORD=1234
    ports:
      - "9042:9042"
    volumes:
      - ./init_cassandra.sh:/init_cassandra.sh
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - "chmod +x /init_cassandra.sh && /init_cassandra.sh && cassandra -f"

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mysql_data: