services:
  postgres:
    container_name: postgres-ox
    image: postgres:15
    environment:
      POSTGRES_USER: ox_user
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432

  keycloak_web:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: ox_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/ox_user
      KC_DB_USERNAME: ox_user
      KC_DB_PASSWORD: 1234

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    depends_on:
      - postgres
    ports:
      - 8080:8080

  mysql:
    image: mysql
    container_name: ox-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  schema-creator:
    image: mysql
    container_name: ox-schema-creator-mysql
    volumes:
      - ./init_mysql.sh:/init_mysql.sh
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - "chmod +x /init_mysql.sh && /init_mysql.sh && mysql -f"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
    depends_on:
      - mysql

  cassandra:
    image: cassandra
    container_name: ox-cassandra
    environment:
      - CASSANDRA_USER=user
      - CASSANDRA_PASSWORD=1234
    ports:
      - "9042:9042"
    volumes:
      - ./init_cassandra.sh:/init_cassandra.sh
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - "chmod +x /init_cassandra.sh && /init_cassandra.sh && cassandra -f"

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=ox_account
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

volumes:
  postgres_data:
  mysql_data:
  mariadb_data:

networks:
  mariadb_network:
    driver: bridge