services:
  postgres:
    container_name: postgres-ox
    image: postgres
    environment:
      POSTGRES_USER: ox
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-ox
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  mysql:
    image: mysql
    container_name: ox-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  schema-creator:
    image: mysql
    container_name: ox-schema-creator-mysql
    volumes:
      - ./init_mysql.sh:/usr/local/bin/init_mysql.sh:ro
    command: [ "bash", "-c", "/usr/local/bin/init_mysql.sh" ]
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1111
    depends_on:
      - mysql

  cassandra:
    image: cassandra
    container_name: ox-cassandra
    environment:
      - CASSANDRA_USER=user
      - CASSANDRA_PASSWORD=1234
    ports:
      - "9042:9042"
    volumes:
      - ./init_cassandra.sh:/init_cassandra.sh
    entrypoint: [ "/init_cassandra.sh" ]
    command: [ "cassandra", "-f" ]


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  mysql_data: